"""Guard the intentional one-GPU reproduction choices and author rules."""
from pathlib import Path

from utils.run_config import load_run_config


ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / "configs" / "gemma2-2b" / "server3090"


def load(name):
    return load_run_config(str(CFG / name))


def test_isft_uses_author_task_hyperparameters_and_one_training_cycle():
    hotpot = load("hotpot_qa_isft.yaml")
    arc = load("arc_isft.yaml")
    assert (hotpot.explore_count, hotpot.max_round, hotpot.max_tokens_per_turn) == (10, 10, 2000)
    assert (hotpot.lambda1, hotpot.lambda2, hotpot.sft.num_train_epochs) == (-0.6, 1.0, 3.0)
    assert (arc.explore_count, arc.max_round, arc.max_tokens_per_turn) == (15, 10, 2000)
    assert (arc.lambda1, arc.lambda2, arc.sft.learning_rate) == (-0.5, 0.6, 1.0e-6)
    assert (hotpot.selection_trim_low, hotpot.selection_trim_high) == (0.0, 0.7)
    assert (arc.selection_trim_low, arc.selection_trim_high) == (0.1, 0.8)
    # iteration 0 trains; iteration 1 is generated by the orchestrator without training.
    assert hotpot.iteration_times == arc.iteration_times == 2


def test_standalone_idpo_starts_from_isft_and_uses_author_mcts_rpo():
    for stem in ("hotpot_qa", "arc"):
        isft = load(f"{stem}_isft.yaml")
        idpo = load(f"{stem}_idpo.yaml")
        assert idpo.alice.initial_model_path == isft.alice_checkpoint_path(0)
        assert idpo.bob.initial_model_path == isft.bob_checkpoint_path(0)
        assert idpo.dpo.author_mcts is True
        assert idpo.dpo.search_iterations == 8
        assert idpo.dpo.rollouts_per_expansion == 3
        assert idpo.dpo.candidate_top_k == 10
        assert idpo.dpo.pair_keep_ratio == 0.5
        assert idpo.dpo.rpo_alpha == 1.0
        assert idpo.dpo.gradient_accumulation_steps == 8
        assert idpo.dpo.max_length == 4096
        assert idpo.dpo.max_prompt_length == 1024


def test_hybrid_uses_standard_dpo_and_author_token_percentile():
    for stem in ("hotpot_qa", "arc"):
        hybrid = load(f"{stem}_hybrid_dpo.yaml")
        assert hybrid.dpo.author_mcts is True
        assert hybrid.dpo.rpo_alpha is None
        assert hybrid.dpo.token_budget_percentile == 0.80
    assert load("hotpot_qa_hybrid_sft.yaml").sft.num_train_epochs == 2.0
    assert load("hotpot_qa_hybrid_dpo.yaml").dpo.max_length == 512
    assert load("arc_hybrid_dpo.yaml").dpo.beta == 0.1


def test_reward_coefficients_match_author_recipes():
    hotpot = load("hotpot_qa_idpo.yaml")
    arc = load("arc_idpo.yaml")
    assert (hotpot.lambda1, hotpot.lambda2, hotpot.dpo.beta) == (-0.6, 1.0, 0.1)
    assert (arc.lambda1, arc.lambda2, arc.dpo.beta) == (-0.4, 0.7, 0.2)
